site_name: Statathon Docs
site_url: https://SoumyaSudhirNayak.github.io/STATATHON_2025/

nav:
  - Home: index.md
  - API Reference: api.md
  - Authentication: auth.md
  - Usage Metering: usage.md

theme:
  name: material
